microservice:
  build: .
  command: "nodejs server.js"
  ports:
    - "8080:80"
  links:
    - rabbitmq
  volumes:
    - ./microservice-nodejs
rabbitmq:
  image: rabbitmq
  ports:
    - "5672:5672"
  expose:
    - "5672"
